// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jUMrEPalhoFcSKvJxZxzMf1dSpHAN8c',
    appId: '1:56062361558:web:0ecba56c03de92a1c52e77',
    messagingSenderId: '56062361558',
    projectId: 'clinica-8d808',
    authDomain: 'clinica-8d808.firebaseapp.com',
    storageBucket: 'clinica-8d808.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRlcVxQZaaGHWXYybJsj9dUYIBgd1K76M',
    appId: '1:56062361558:android:2ff6ab6ccd67f031c52e77',
    messagingSenderId: '56062361558',
    projectId: 'clinica-8d808',
    storageBucket: 'clinica-8d808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01as2d944K1b0LK2CEDYic8CdLy5aw9M',
    appId: '1:56062361558:ios:c94503abb58081f6c52e77',
    messagingSenderId: '56062361558',
    projectId: 'clinica-8d808',
    storageBucket: 'clinica-8d808.appspot.com',
    iosBundleId: 'com.ucv.clinica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01as2d944K1b0LK2CEDYic8CdLy5aw9M',
    appId: '1:56062361558:ios:c94503abb58081f6c52e77',
    messagingSenderId: '56062361558',
    projectId: 'clinica-8d808',
    storageBucket: 'clinica-8d808.appspot.com',
    iosBundleId: 'com.ucv.clinica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1jUMrEPalhoFcSKvJxZxzMf1dSpHAN8c',
    appId: '1:56062361558:web:ffe85d93100870a5c52e77',
    messagingSenderId: '56062361558',
    projectId: 'clinica-8d808',
    authDomain: 'clinica-8d808.firebaseapp.com',
    storageBucket: 'clinica-8d808.appspot.com',
  );
}
